### ISSUE TITLE
Show yaml full key

### ISSUE THREAD

**Issue by kazuooooo** [kazuooooo/yaml-X#2]
Want to yaml full key on focus a key on yaml file.
And should be able to copy a full key from some action.

For example

```yaml
very:
  long:
  ......
    yaml:
       key: "value" // When focus here, you can copy very.long.yaml.key
```
